### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by ThomasSeeker** [adrienluitot/surfshark-linux-client#11]
Hey there, 

I would really like to try the surfshark-client.

All the installation commands went through smoothly.

Only the last one (python surfshark_client.py) gives this error: 

`Traceback (most recent call last):
File "surfshark_client.py", line 6, in <module>
import urllib.request
ImportError: No module named request
`

Can you help me with this, please?

Best greetings from Germany!
Thomas

**Comment by adrienluitot** [comment]
Hello ! :wave: 

Firstly, I'm sorry for the late answer, I hadn't seen your issue.

I never faced this issue so I made a quick search on the internet.
It seems that you might run the code with python2 instead of python 3.

**Comment by ThomasSeeker** [comment]
Hey! 

Thank you for replying!

Yes, I found this answer too. But what I don't understand:

I seem to have both pythons installed.

python3 -V ... gives this output:
Python 3.5.2

And: 
python2 -V ... gives this output:
Python 2.7.12

Is this even possible? To have both?

**Comment by adrienluitot** [comment]
Hello!

Yes, it is possible, and it's often the case.
Normally you should have a default version, that you can see with `python -V`, if you are on linux you can change it with symbolic links.
Otherwise, you can launch the app with `python3` instead of `python` or `python2`.

**Comment by ThomasSeeker** [comment]
Thank you for your help!

It turns out, my python 3.5.2 is also too old for this. 

And since I have to upgrade my system soon anyways, I will wait for that ... and come back later!

Thanks again!

**Comment by adrienluitot** [comment]
You are welcome!

Okay okay, good luck. See you!
