### ISSUE TITLE
No Module "Crypto"

### ISSUE THREAD

**Issue by 0x3mi** [adrienluitot/surfshark-linux-client#13]
Hey folks, i got an issue here: 

Traceback (most recent call last):
  File "/home/name/Programme/surfshark/surfshark-linux-client/surfshark_client.py", line 16, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

i tried to open the  programm with "sudo python3 surfshark_client.py" and this error showed up.

**Comment by adrienluitot** [comment]
Hello, sorry I didn't see your issue >.<
Have you installed the libs in [requirements.txt](https://github.com/adrienluitot/surfshark-linux-client/blob/master/requirements.txt)?

**Comment by kcvanderlinden** [comment]
same issue, installed the requirements.txt.

**Comment by kcvanderlinden** [comment]
solved it already. the GUI has to be run as root (because of VPN capability). Therefore the package Cryptodome needs also to be installed with root permissions. Thus 

- install requirements with : `sudo pip install -r requirements.txt`
- run app with: `sudo python surfshark_client.py`

**Comment by adrienluitot** [comment]
Good! Thanks for your feedback!
It's been such a long time I haven't use this project... I am astonished it still works haha

And yes root permissions are necessary.

I will close this issue if it's fixed.
